
# tap repositories and their packages

tap homebrew/core
brew adwaita-icon-theme
brew aircrack-ng
brew ansible
brew aom
brew apr
brew apr-util
brew argon2
brew aspell
brew atk
brew autoconf
brew autogen
brew automake
brew bash-completion
brew bdw-gc
brew bison
brew boost
brew brew-cask-completion
brew brew-gem
brew brew-pip
brew brotli
brew bundler-completion
brew c-ares
brew cabal-install
brew cabextract
brew cairo
brew ceres-solver
brew check
brew cmake
brew composer
brew coreutils
brew ctags
brew curl
brew curl-openssl
brew dbus
brew docker
brew docker-compose
brew doxygen
brew dylibbundler
brew eigen
brew ext4fuse
brew faac
brew faad2
brew ffmpeg
brew flac
brew fontconfig
brew freetds
brew freetype
brew frei0r
brew fribidi
brew gawk
brew gcc
brew gd
brew gdb
brew gdbm
brew gdk-pixbuf
brew gettext
brew gflags
brew ghc
brew ghostscript
brew gibo
brew giflib
brew git
brew git-flow
brew git-lfs
brew glib
brew glib-networking
brew glog
brew gmp
brew gnu-getopt
brew gnutls
brew go
brew gobject-introspection
brew gradle
brew gradle-completion
brew graphite2
brew graphviz
brew gsettings-desktop-schemas
brew gst-libav
brew gst-plugins-bad
brew gst-plugins-base
brew gst-plugins-good
brew gst-plugins-ugly
brew gstreamer
brew gtk+3
brew gtk-vnc
brew gtksourceview4
brew gts
brew guile
brew harfbuzz
brew hicolor-icon-theme
brew httpd
brew icu4c
brew ilmbase
brew imagemagick
brew intltool
brew isl
brew jansson
brew jasper
brew jemalloc
brew jpeg
brew jq
brew json-glib
brew lame
brew ldns
brew leptonica
brew lha
brew libarchive
brew libass
brew libbluray
brew libcroco
brew libde265
brew libepoxy
brew libev
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libheif
brew libiconv
brew libidn
brew libidn2
brew libmetalink
brew libmms
brew libmpc
brew libnice
brew libogg
brew libomp
brew libosinfo
brew libpng
brew libpq
brew libpsl
brew librsvg
brew libsamplerate
brew libshout
brew libsndfile
brew libsodium
brew libsoup
brew libsoxr
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvirt
brew libvirt-glib
brew libvorbis
brew libvpx
brew libvterm
brew libxml2
brew libyaml
brew libzip
brew little-cms2
brew llvm
brew lua
brew luajit
brew lv
brew lz4
brew lzo
brew mas
brew metis
brew mono
brew mpfr
brew msgpack
brew mupdf
brew ncurses
brew neovim
brew netpbm
brew nettle
brew nghttp2
brew ninja
brew node
brew ntfs-3g
brew numpy
brew oniguruma
brew openblas
brew opencore-amr
brew opencv
brew openexr
brew openjpeg
brew openldap
brew openmotif
brew openssh
brew openssl
brew openssl@1.1
brew opus
brew orc
brew p11-kit
brew p7zip
brew pandoc
brew pandoc-citeproc
brew pandoc-crossref
brew pango
brew pcre
brew pcre2
brew pdf2htmlex
brew perl
brew php
brew php-code-sniffer
brew pixman
brew pkg-config
brew postgresql
brew py2cairo
brew py3cairo
brew pyenv
brew pygobject3
brew pyqt
brew python
brew python@2
brew qpdf
brew qt
brew rbenv
brew readline
brew rename
brew rtmpdump
brew rubberband
brew ruby
brew ruby-build
brew ruby-completion
brew scriptcs
brew sdl2
brew shared-mime-info
brew sip
brew smartmontools
brew snappy
brew speex
brew sphinx-doc
brew spice-gtk
brew spice-protocol
brew sqlite
brew srtp
brew ssh-copy-id
brew suite-sparse
brew swig
brew taglib
brew tbb
brew tesseract
brew testdisk
brew theora
brew tidy-html5
brew tmux
brew trash
brew tree
brew ttfautohint
brew unbound
brew unibilium
brew unixodbc
brew unrar
brew usbredir
brew vagrant-completion
brew vala
brew vim
brew vte3
brew webp
brew wget
brew whois
brew wine
brew winetricks
brew x264
brew x265
brew xvid
brew xz
brew yajl
brew youtube-dl
brew zenity

tap homebrew/cask-versions

tap homebrew/services

tap homebrew/cask
cask 0xed
cask amazon-music
cask au-lab
cask console
cask docker
cask dropbox
cask gimp
cask google-backup-and-sync
cask google-japanese-ime
cask inkscape
cask karabiner-elements
cask kodi
cask mactex
cask microsoft-teams
cask nosleep
cask oracle-jdk
cask phantomjs
cask sequel-pro
cask shupapan
cask slack
cask soundflowerbed
cask steam
cask vagrant
cask virtualbox
cask visual-studio
cask vlc
cask wavesurfer
cask xquartz

tap jeffreywildman/virt-manager
brew osinfo-db
brew osinfo-db-tools
brew virt-manager
brew virt-viewer

tap mas-cli/tap

tap rcmdnk/file
brew brew-file

# Other pip packages
pip completion

# Other Cask applications
cask adobe-air
cask android-file-transfer
cask balenaetcher
cask coteditor
cask dotnet-sdk
cask gdisk
cask gitup
cask google-chrome
cask google-web-designer
cask java
cask java8
cask keka
cask licecap
cask microsoft-office
cask mono-mdk
cask onyx
cask osxfuse
cask prince
cask sequential
cask skim
cask soundflower
cask sourcetree
cask the-unarchiver
cask vagrant-manager
cask virtualbox-extension-pack
cask visual-studio-code
cask voxengo-span-au
cask wireshark

# App Store applications
appstore 926707738 Countdowns (1.3.2)
appstore 847809913 Download Shuttle (2.4)
appstore 682658836 GarageBand (10.3.2)
appstore 408981434 iMovie (10.1.12)
appstore 408981381 iPhoto (9.6.1)
appstore 472226235 LanScan (6.2.1)
appstore 409201541 Pages (8.1)
appstore 803453959 Slack (4.0.3)
appstore 497799835 Xcode (10.3)
